name: Reusable Deploy

on:

  workflow_call:

    inputs:

      repository:
        required: true
        type: string

      environment:
        required: true
        type: string

      issue:
        required: false
        type: string

    secrets:

      CHANGEMANGEMENTTOKEN:
        required: true

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Lanzar workflow remoto

        uses: actions/github-script@v7

        with:

          github-token: ${{ secrets.CHANGEMANGEMENTTOKEN }}

          script: |

            await github.rest.actions.createWorkflowDispatch({

              owner: context.repo.owner,

              repo: '${{ inputs.repository }}',

              workflow_id: 'deploy.yml',

              ref: 'main',

              inputs: {

                environment: '${{ inputs.environment }}',

                issue: '${{ inputs.issue }}'

              }

            })

      - name: Confirmacion

        run: |
          echo "Workflow remoto lanzado"
          echo "Repositorio: ${{ inputs.repository }}"
          echo "Ambiente: ${{ inputs.environment }}"
          echo "Issue: ${{ inputs.issue }}"
