name: Ticket Regular

on:
  workflow_call:

    inputs:

      issue_number:
        required: true
        type: string

      issue_title:
        required: true
        type: string

      issue_author:
        required: true
        type: string

jobs:

  solicitud_pase:

    runs-on: ubuntu-latest

    steps:

      - name: Inicializar solicitud

        run: |
          echo "Issue Regular recibida"
          echo "Numero: ${{ inputs.issue_number }}"
          echo "Titulo: ${{ inputs.issue_title }}"
          echo "Solicitante: ${{ inputs.issue_author }}"

  stage_revision_checklist:

    needs: solicitud_pase

    runs-on: ubuntu-latest

    environment: Revision-Checklist

    steps:

      - run: echo "Checklist aprobado"

  stage_aprobacion_seguridad:

    needs: stage_revision_checklist

    runs-on: ubuntu-latest

    environment: Aprobacion-Seguridad

    steps:

      - run: echo "Seguridad aprobada"

  stage_planificacion_y_configuracion_dataops:

    needs: stage_aprobacion_seguridad

    runs-on: ubuntu-latest

    environment: Planificacion-Ambiente-DataOps

    steps:

      - run: echo "Planificacion aprobada"

  deploy_cert:

    needs: stage_planificacion_y_configuracion_dataops

    uses: ./.github/workflows/deploy-cert.yml

    secrets: inherit

    with:

      repository: SquadCredicorpData

      environment: CERT

  stage_validacion_funcional_cert:

    needs: deploy_cert

    runs-on: ubuntu-latest

    environment: Validacion-Funcional-Certificacion

    steps:

      - run: |
          echo "Validacion funcional CERT completada"
          echo "Aprobado para Produccion"

  deploy_prod:

    needs: stage_validacion_funcional_cert

    uses: ./.github/workflows/deploy-prod.yml

    secrets: inherit

    with:

      repository: SquadCredicorpData

      environment: PROD

  stage_validacion_tecnica_prod:

    needs: deploy_prod

    runs-on: ubuntu-latest

    environment: Validacion-Tecnica-Produccion

    steps:

      - run: |
          echo "Validando logs"
          echo "Validando jobs"
          echo "Validando pipelines"
          echo "Validacion tecnica OK"

  stage_validacion_funcional_prod:

    needs: stage_validacion_tecnica_prod

    runs-on: ubuntu-latest

    environment: Validacion-Funcional-Produccion

    steps:

      - run: |
          echo "Validacion funcional de negocio"
          echo "Validacion funcional OK"

  notificar_rechazo:

    needs:
      - stage_revision_checklist
      - stage_aprobacion_seguridad
      - stage_planificacion_y_configuracion_dataops
      - deploy_cert
      - stage_validacion_funcional_cert
      - deploy_prod
      - stage_validacion_tecnica_prod
      - stage_validacion_funcional_prod

    if: failure()

    runs-on: ubuntu-latest

    steps:

      - run: |
          echo "El flujo Regular se detuvo por rechazo o error"
